name: stac_dsl_example
description: Examples for using the STAC DSL library
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  stac_dsl:
    path: ../
  args: ^2.4.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
